ci: update integration to the latest master (openssh-client)
Avoid the following error:

ERROR: unable to select packages:
  openssh-client-common-9.0_p1-r1:
    breaks: openssh-client-default-9.0_p1-r2[openssh-client-common=9.0_p1-r2]

Changelog: None
Ticket: None

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>